# PANDAS

Pandas is a software library written for the Python programming language for **data manipulation and analysis**. In particular, it offers data structures and operations for manipulating numerical tables and time series.

In [122]:
import pandas as pd

## DataFrames 

The data structures that store data in pandas are the **Data Frames**.

In [123]:
df1 = pd.DataFrame([[2, 4, 6],  [10, 20, 30]])
df1

0   1   2
0   2   4   6
1  10  20  30

The 0, 1, 2 at top are the **column names** (you can name the columns yourself) and the 0 and 1 in the right are the indices (which also can be renamed)

In [124]:
df1 = pd.DataFrame([[2, 4, 6],  [10, 20, 30]], columns = ["Column1", "Columns2", "Column3"], index= ["Row1", "Row2"])
df1

Column1  Columns2  Column3
Row1        2         4        6
Row2       10        20       30

See..... the names

Though the customized indices don't make much sense ... but hey! you can do it, if you want to (dunno why).

Another way of creating Data Frames is to use dictonaries instead of lists

In [125]:
df2 = pd.DataFrame([{"Last Name" : "Bond", "Name" : "James"}, {"Last Name" : "Stark", "Name" : "Tony"}, {"Last Name" : "Anderson", "Name" : "Thomas"},{"Last Name" : "Holmes", "Name" : "Sherlock"},{"Name" : "Neo"}])
print(type(df2))
df2

<class 'pandas.core.frame.DataFrame'>


Last Name      Name
0      Bond     James
1     Stark      Tony
2  Anderson    Thomas
3    Holmes  Sherlock
4       NaN       Neo

This also goes on to prove how idiotic it is to create data frames using these ways (manually). We mostly use externally created csv's or other files to import data for analysis and processing using pandas

Also, notice the data type of df2!

In [126]:
print("The column-wise mean of the data in first data frame")
print(df1.mean())
print("\nAnd the mean of entire data set is")
print(df1.mean().mean())

The column-wise mean of the data in first data frame
Column1      6.0
Columns2    12.0
Column3     18.0
dtype: float64

And the mean of entire data set is
12.0


And this an (very, very, very leyman level) exampleof data analysis

## Series

In [127]:
type(df1.mean())

pandas.core.series.Series

Well this is a pandas' **Series** object. Series have more or less the same methonds that we can apply on a data frame object.

Data Frames are made up of series. You'll get a gist once you see the below code and its result

In [128]:
print("Data type of the columns of a Data Frame is",type(df1.Column1))
print("Thus we can find their mean or do other (I don't know what) stuff on them.\nLike the mean of Column1 is", df1.Column1.mean(),"\nAnd the largest element of Column1 is", df1.Column1.max())

Data type of the columns of a Data Frame is <class 'pandas.core.series.Series'>
Thus we can find their mean or do other (I don't know what) stuff on them.
Like the mean of Column1 is 6.0 
And the largest element of Column1 is 10


## Working with files/data

### CSV files

Working with **csv's** and other file formats

In [129]:
df1 = pd.read_csv("Dataset\supermarkets.csv")
df1

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

Wasn't that easy and simple!

### json files

In [130]:
df2 = pd.read_json("Dataset\supermarkets.json")
df2

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

### Exel files

Loading **Exel** files

In [131]:
df3 = pd.read_excel("Dataset\supermarkets.xlsx", sheet_name = 0)
df3

ID          Address           City             State Country  \
0   1     3666 21st St  San Francisco          CA 94114     USA   
1   2   735 Dolores St  San Francisco          CA 94119     USA   
2   3      332 Hill St  San Francisco  California 94114     USA   
3   4     3995 23rd St  San Francisco          CA 94114     USA   
4   5  1056 Sanchez St  San Francisco        California     USA   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   

  Supermarket Name  Number of Employees  
0          Madeira                    8  
1      Bready Shop                   15  
2      Super River                   25  
3       Ben's Shop                   10  
4          Sanchez                   12  
5       Richvalley                   20

### Plain files

From **Plain txt** files (seperated by commas) we use *pandas.read_csv()* 

This is not technically a csv (comma seperated) but rather a *character seperated* and in case of comma we don't need to pass anyy **seperator** arguement but for other separators we need to pass the character that is used as a separator

In [132]:
df4 = pd.read_csv("Dataset\supermarkets-commas.txt")
df4

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

Below we can check what happens if we use something other than comma as a separator

In [133]:
df4 = pd.read_csv("Dataset\supermarkets-semi-colons.txt")
df4

ID;Address;City;State;Country;Name;Employees
0  1;3666 21st St;San Francisco;CA 94114;USA;Made...
1  2;735 Dolores St;San Francisco;CA 94119;USA;Br...
2  3;332 Hill St;San Francisco;California 94114;U...
3  4;3995 23rd St;San Francisco;CA 94114;USA;Ben'...
4  5;1056 Sanchez St;San Francisco;California;USA...
5  6;551 Alvarado St;San Francisco;CA 94114;USA;R...

Well, that came out crappy. I didn't recognize the separator.

So what do we do

In [134]:
df5 = pd.read_csv("Dataset\supermarkets-semi-colons.txt", sep = ';')
df5

ID          Address           City             State Country          Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA       Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA   Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA   Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA    Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA       Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA    Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

It worked!

### Headers 

Setting table **Header Row**

When data is imported in the code, the first row of the data is treated as the header row by default and so if data is missing header row it will create something like this

In [135]:
df6 = pd.read_csv("Dataset\supermarkets_noH.csv")
print(df6.sum())
df6

1                                                               20
3666 21st St     735 Dolores St332 Hill St3995 23rd St1056 Sanc...
San Francisco    San FranciscoSan FranciscoSan FranciscoSan Fra...
CA 94114         CA 94119California 94114CA 94114CaliforniaCA 9...
USA                                                USAUSAUSAUSAUSA
Madeira          Bready ShopSuper RiverBen's ShopSanchezRichvalley
8                                                               82
dtype: object


1     3666 21st St  San Francisco          CA 94114  USA      Madeira   8
0  2   735 Dolores St  San Francisco          CA 94119  USA  Bready Shop  15
1  3      332 Hill St  San Francisco  California 94114  USA  Super River  25
2  4     3995 23rd St  San Francisco          CA 94114  USA   Ben's Shop  10
3  5  1056 Sanchez St  San Francisco        California  USA      Sanchez  12
4  6  551 Alvarado St  San Francisco          CA 94114  USA   Richvalley  20

Well, what the heck

So we need to explicitly tell the code that the data lacks a header row by setting the **header** parameter as ***header = None***

In [136]:
df7 = pd.read_csv("Dataset\supermarkets_noH.csv", header = None)
print(df7.sum(axis = 1))    #row-wise
print(df7.sum(axis = 0))    #column-wise
df7

0     9
1    17
2    28
3    14
4    17
5    26
dtype: int64
0                                                   21
1    3666 21st St735 Dolores St332 Hill St3995 23rd...
2    San FranciscoSan FranciscoSan FranciscoSan Fra...
3    CA 94114CA 94119California 94114CA 94114Califo...
4                                   USAUSAUSAUSAUSAUSA
5    MadeiraBready ShopSuper RiverBen's ShopSanchez...
6                                                   90
dtype: object


0                1              2                 3    4            5   6
0  1     3666 21st St  San Francisco          CA 94114  USA      Madeira   8
1  2   735 Dolores St  San Francisco          CA 94119  USA  Bready Shop  15
2  3      332 Hill St  San Francisco  California 94114  USA  Super River  25
3  4     3995 23rd St  San Francisco          CA 94114  USA   Ben's Shop  10
4  5  1056 Sanchez St  San Francisco        California  USA      Sanchez  12
5  6  551 Alvarado St  San Francisco          CA 94114  USA   Richvalley  20

So this tells the code that we don't havfe a header so it will give a generic header which will be made up of number indices.

We can initialize the column and row names as we did earlier or like this

### Naming columns

In [137]:
df7.columns = ["ID", "Address", "City", "ZIP", "Country", "Name", "Employees"]
df7

ID          Address           City               ZIP Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

We may want to make a given attribute of the data as the column index, like *ID* in this above data frame.

We can do this using the ***dataframe.set_index("name")*** method which *returns a **new*** dataframe 

In [138]:
df7.set_index("ID")

Address           City               ZIP Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  
ID             
1           8  
2          15  
3          25  
4          10  
5          12  
6          20

the initial df7 is still unchanged => We need to save the output of the set_index function in some var or we need to se the **inplace** parameter of the set_index function to **True**

In [139]:
df8 = df7.set_index("ID")
df7

ID          Address           City               ZIP Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

### **But a word of caution**

In [140]:
df8.set_index("Address", inplace= True)

Now when we change the index (here we set it to Address), the new index will be set but the old index is not reassigned as a column rather is dropped or deleted

In [141]:
df8

City               ZIP Country         Name  \
Address                                                                 
3666 21st St     San Francisco          CA 94114     USA      Madeira   
735 Dolores St   San Francisco          CA 94119     USA  Bready Shop   
332 Hill St      San Francisco  California 94114     USA  Super River   
3995 23rd St     San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St  San Francisco        California     USA      Sanchez   
551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

                 Employees  
Address                     
3666 21st St             8  
735 Dolores St          15  
332 Hill St             25  
3995 23rd St            10  
1056 Sanchez St         12  
551 Alvarado St         20

What we can do to tackle it is set **drop** parameter to ***False*** so that the attribute we set as index will also remain as a column so that later on if we change the index we'll still have the data that was earlier used for indexing

In [142]:
df8.set_index("Name", inplace= True, drop= False)

See that Name has become an index but it will also remain as a column

In [143]:
df8

City               ZIP Country         Name  Employees
Name                                                                        
Madeira      San Francisco          CA 94114     USA      Madeira          8
Bready Shop  San Francisco          CA 94119     USA  Bready Shop         15
Super River  San Francisco  California 94114     USA  Super River         25
Ben's Shop   San Francisco          CA 94114     USA   Ben's Shop         10
Sanchez      San Francisco        California     USA      Sanchez         12
Richvalley   San Francisco          CA 94114     USA   Richvalley         20

## Filtering Data

Indexing and extracting data

We'll use df7 data frame to work upon

In [144]:
df7

ID          Address           City               ZIP Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [145]:
data = df7.set_index("Address", drop=True)
data

ID           City               ZIP Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees  
Address                     
3666 21st St             8  
735 Dolores St          15  
332 Hill St             25  
3995 23rd St            10  
1056 Sanchez St         12  
551 Alvarado St         20

We can use *label based* or *position based* indexing

**Lable based indexing** is when we use the row and column indices for addressing them

In [146]:
data.loc["735 Dolores St" : "3995 23rd St", "Country" : "Name"]

Country         Name
Address                            
735 Dolores St     USA  Bready Shop
332 Hill St        USA  Super River
3995 23rd St       USA   Ben's Shop

And specific elements using

In [147]:
data.loc["332 Hill St", "Country"]

'USA'

And for all the columns

In [148]:
list(data.loc[:, "Country"])   #And the list function of python will convert it in a list

TypeError: 'list' object is not callable

**Position based indexing** obviously the much better (real) way

In [ ]:
data

ID           City               ZIP Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees  
Address                     
3666 21st St             8  
735 Dolores St          15  
332 Hill St             25  
3995 23rd St            10  
1056 Sanchez St         12  
551 Alvarado St         20

In [ ]:
data.iloc[1:3, 1:3]   #and as usual it is upper-bound exclusive

City               ZIP
Address                                        
735 Dolores St  San Francisco          CA 94119
332 Hill St     San Francisco  California 94114

In [ ]:
data.iloc[:, 1:3]

City               ZIP
Address                                         
3666 21st St     San Francisco          CA 94114
735 Dolores St   San Francisco          CA 94119
332 Hill St      San Francisco  California 94114
3995 23rd St     San Francisco          CA 94114
1056 Sanchez St  San Francisco        California
551 Alvarado St  San Francisco          CA 94114

In [ ]:
data.iloc[3, 1:3]

City    San Francisco
ZIP          CA 94114
Name: 3995 23rd St, dtype: object

We can also get rid of columns and rows of data frames (though these operations are not inplace, ie, they will create a new instance rather than modifying the object on which they were invoked)

In [ ]:
data

ID           City               ZIP Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees  
Address                     
3666 21st St             8  
735 Dolores St          15  
332 Hill St             25  
3995 23rd St            10  
1056 Sanchez St         12  
551 Alvarado St         20

### Deleting elements (dataframe.drop())

The **1** in the arguement of ***dataframe.drop()*** function tells that we want to delete the column and 0 implies we intend to delete rows

In [ ]:
data.drop("City", 1) # 

ID               ZIP Country         Name  Employees
Address                                                              
3666 21st St      1          CA 94114     USA      Madeira          8
735 Dolores St    2          CA 94119     USA  Bready Shop         15
332 Hill St       3  California 94114     USA  Super River         25
3995 23rd St      4          CA 94114     USA   Ben's Shop         10
1056 Sanchez St   5        California     USA      Sanchez         12
551 Alvarado St   6          CA 94114     USA   Richvalley         20

**0** removes rows

In [ ]:
data.drop("332 Hill St", 0)

ID           City         ZIP Country         Name  Employees
Address                                                                       
3666 21st St      1  San Francisco    CA 94114     USA      Madeira          8
735 Dolores St    2  San Francisco    CA 94119     USA  Bready Shop         15
3995 23rd St      4  San Francisco    CA 94114     USA   Ben's Shop         10
1056 Sanchez St   5  San Francisco  California     USA      Sanchez         12
551 Alvarado St   6  San Francisco    CA 94114     USA   Richvalley         20

To drop columns or rows based on indexing, we do a trick

Example for rows is below

In [ ]:
data.drop(data.index[0:3], 0)

ID           City         ZIP Country        Name  Employees
Address                                                                      
3995 23rd St      4  San Francisco    CA 94114     USA  Ben's Shop         10
1056 Sanchez St   5  San Francisco  California     USA     Sanchez         12
551 Alvarado St   6  San Francisco    CA 94114     USA  Richvalley         20

Similarly for columns

In [ ]:
data.drop(data.columns[0:3], 1)

Country         Name  Employees
Address                                        
3666 21st St        USA      Madeira          8
735 Dolores St      USA  Bready Shop         15
332 Hill St         USA  Super River         25
3995 23rd St        USA   Ben's Shop         10
1056 Sanchez St     USA      Sanchez         12
551 Alvarado St     USA   Richvalley         20

***dataframe.index*** returns a list of names of all the index columns and ***dataframe.columns*** returns a series of names of all the names of columns

In [ ]:
print(data.index,"\n")
print(data.columns)

Index(['3666 21st St', '735 Dolores St', '332 Hill St', '3995 23rd St',
       '1056 Sanchez St', '551 Alvarado St'],
      dtype='object', name='Address') 

Index(['ID', 'City', 'ZIP', 'Country', 'Name', 'Employees'], dtype='object')


## Updating and adding **Series**

### Adding Columns

!When adding new column of data to a data frame, we need to declare the column name and then assign a list of data values corresponding to each row (=>number of values in the list should be equal to the number of rows in the data frame)

In [ ]:
data["Continent"] = ["North America"] * data.shape[0]    #Or just multiply by len(data.index)
data

ID           City               ZIP Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees      Continent  
Address                                    
3666 21st St             8  North America  
735 Dolores St          15  North America  
332 Hill St             25  North America  
3995 23rd St            10  North America  
1056 Sanchez St         12  North America  
551 Alvarado St         20  North America

### Modifying a column

In [ ]:
data["Continent"] = data["Country"] + ", " + "North America"
data

ID           City               ZIP Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees           Continent  
Address                                         
3666 21st St             8  USA, North America  
735 Dolores St          15  USA, North America  
332 Hill St             25  USA, North America  
3995 23rd St            10  USA, North America  
1056 Sanchez St         12  USA, North America  
551 Alvarado St         20  USA, North America

### Adding a row

This ain't veryy easy as there isn't a simple way of passing a row to a data frame. So one way to doing this is to **transpose** the data frame and then adding a column like we did previously and then transpose it back

In [ ]:
data_temp = data.T
data_temp

Address          3666 21st St      735 Dolores St         332 Hill St  \
ID                          1                   2                   3   
City            San Francisco       San Francisco       San Francisco   
ZIP                  CA 94114            CA 94119    California 94114   
Country                   USA                 USA                 USA   
Name                  Madeira         Bready Shop         Super River   
Employees                   8                  15                  25   
Continent  USA, North America  USA, North America  USA, North America   

Address          3995 23rd St     1056 Sanchez St     551 Alvarado St  
ID                          4                   5                   6  
City            San Francisco       San Francisco       San Francisco  
ZIP                  CA 94114          California            CA 94114  
Country                   USA                 USA                 USA  
Name               Ben's Shop             Sanchez          Richvalley  
Employees                  10                  12                  20  
Continent  USA, North America  USA, North America  USA, North America

In [ ]:
data_temp["My Address"] = [7, "My City", "Myy ZIP code", "My Country", "My Name", 67, "My Continent"]
data = data_temp.T
data

ID           City               ZIP     Country         Name  \
Address                                                                        
3666 21st St     1  San Francisco          CA 94114         USA      Madeira   
735 Dolores St   2  San Francisco          CA 94119         USA  Bready Shop   
332 Hill St      3  San Francisco  California 94114         USA  Super River   
3995 23rd St     4  San Francisco          CA 94114         USA   Ben's Shop   
1056 Sanchez St  5  San Francisco        California         USA      Sanchez   
551 Alvarado St  6  San Francisco          CA 94114         USA   Richvalley   
My Address       7        My City      Myy ZIP code  My Country      My Name   

                Employees           Continent  
Address                                        
3666 21st St            8  USA, North America  
735 Dolores St         15  USA, North America  
332 Hill St            25  USA, North America  
3995 23rd St           10  USA, North America  
1056 Sanchez St        12  USA, North America  
551 Alvarado St        20  USA, North America  
My Address             67        My Continent

Aaaaand we successfully added a row to our data frame

And to update the data of a row we can do similar thing

### Modifying rows

In [ ]:
data = data.T
data["My Address"] = [7, "Varanasi", "VNS 221003", "India", "Hattori", "1", "Asia"]
data = data.T
data

ID           City               ZIP Country         Name  \
Address                                                                    
3666 21st St     1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St   2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St      3  San Francisco  California 94114     USA  Super River   
3995 23rd St     4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St  5  San Francisco        California     USA      Sanchez   
551 Alvarado St  6  San Francisco          CA 94114     USA   Richvalley   
My Address       7       Varanasi        VNS 221003   India      Hattori   

                Employees           Continent  
Address                                        
3666 21st St            8  USA, North America  
735 Dolores St         15  USA, North America  
332 Hill St            25  USA, North America  
3995 23rd St           10  USA, North America  
1056 Sanchez St        12  USA, North America  
551 Alvarado St        20  USA, North America  
My Address              1                Asia

# Example of Data Analysis (Very very basic)

Some tid bids:  The process of converting addresses into latitudes and longitudes is called **Geocoding** and the process of converting latitude and longitude info of a place into address is called **Reverse geocoding**

In [ ]:
from geopy.geocoders import ArcGIS
nom = ArcGIS()

In [ ]:
n = nom.geocode("Nav Sadhana Kendra, Varanasi, 221003, Uttar Pradesh")
print(type(n))
n

<class 'geopy.location.Location'>


Location(Nava Sadhana Kala Kendra, (25.372200000000078, 82.92787000000004, 0.0))

Oh WoW! it works

Don't worry about the 0.0 in the end. It's just a response from the geocoder and doesn't mean much. Sometimes it may give a None object in case the location is incorrect (oooorr... its top secret).

Also also, isn't the type of location is interesting, it is an especial object, location object of geopy. Let's extract the latitude and longitude data from it

In [ ]:
print(n.latitude, n.longitude)

25.372200000000078 82.92787000000004


Now lets convert an entire dataframe of addresses into latitudes and longitudes and then add two columns of the extracted information to the data frame

In [ ]:
data = pd.read_csv("Dataset\supermarkets.csv")
data

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

Well the geocoder expects from us a string as an input usually of form "road, city, zip code, country". Basically an address string and not a dataframe. So, lets modify the address column to meet our requirements and then pass the data to the geocoder

In [ ]:
data["Address"] = data["Address"] + ", " + data["City"] + ", " + data["State"] + ", " + data["Country"]
data

ID                                            Address           City  \
0   1         3666 21st St, San Francisco, CA 94114, USA  San Francisco   
1   2       735 Dolores St, San Francisco, CA 94119, USA  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, USA  San Francisco   
3   4         3995 23rd St, San Francisco, CA 94114, USA  San Francisco   
4   5    1056 Sanchez St, San Francisco, California, USA  San Francisco   
5   6      551 Alvarado St, San Francisco, CA 94114, USA  San Francisco   

              State Country         Name  Employees  
0          CA 94114     USA      Madeira          8  
1          CA 94119     USA  Bready Shop         15  
2  California 94114     USA  Super River         25  
3          CA 94114     USA   Ben's Shop         10  
4        California     USA      Sanchez         12  
5          CA 94114     USA   Richvalley         20

## The **dataframe.apply** function

You might be thinking of iterating, but with pandas you don't need to do that as pandas has some functions that allows you to apply a method to all the rows of a dataframe. To do that we need to create a new column/series and then assign it the output of data["column to apply on"].**apply(function name)**

In [ ]:
data["Coordinates"] = data["Address"].apply(nom.geocode)
data

ID                                            Address           City  \
0   1         3666 21st St, San Francisco, CA 94114, USA  San Francisco   
1   2       735 Dolores St, San Francisco, CA 94119, USA  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, USA  San Francisco   
3   4         3995 23rd St, San Francisco, CA 94114, USA  San Francisco   
4   5    1056 Sanchez St, San Francisco, California, USA  San Francisco   
5   6      551 Alvarado St, San Francisco, CA 94114, USA  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                         Coordinates  
0  (3666 21st St, San Francisco, California, 9411...  
1  (735 Dolores St, San Francisco, California, 94...  
2  (332 Hill St, San Francisco, California, 94114...  
3  (3995 23rd St, San Francisco, California, 9411...  
4  (1056 Sanchez St, San Francisco, California, 9...  
5  (551 Alvarado St, San Francisco, California, 9...

Now the coordinates column of the dataframe contains the location objects corresponding to the addresses 

Now to add two more columns to save the latitude and the longitudes of the data points separately we'll use **apply** method in conj7uction with a lambda expression

In [ ]:
data["Latitude"] = data["Coordinates"].apply(lambda x : x.latitude if x != None else None)  # added a conditional just to be sure that the scrip doesn't crash in case someone played a trick with us or made an honest mistake 
data["Longitude"] = data["Coordinates"].apply(lambda x : x.longitude if x != None else None)
data

ID                                            Address           City  \
0   1         3666 21st St, San Francisco, CA 94114, USA  San Francisco   
1   2       735 Dolores St, San Francisco, CA 94119, USA  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, USA  San Francisco   
3   4         3995 23rd St, San Francisco, CA 94114, USA  San Francisco   
4   5    1056 Sanchez St, San Francisco, California, USA  San Francisco   
5   6      551 Alvarado St, San Francisco, CA 94114, USA  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                         Coordinates   Latitude   Longitude  
0  (3666 21st St, San Francisco, California, 9411...  37.756632 -122.429411  
1  (735 Dolores St, San Francisco, California, 94...  37.757829 -122.425373  
2  (332 Hill St, San Francisco, California, 94114...  37.755845 -122.428813  
3  (3995 23rd St, San Francisco, California, 9411...  37.752921 -122.431703  
4  (1056 Sanchez St, San Francisco, California, 9...  37.752132 -122.430006  
5  (551 Alvarado St, San Francisco, California, 9...  37.753582 -122.433234

# Numerical and Scientific Computing with Numpy

## What is Numpy?

NumPy is the fundamental package for scientific computing in Python. NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. 

In [ ]:
import numpy as np

## The numpy object: *ndarray*
At the core of the NumPy package, is the **ndarray** object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. 

**Axis or the dimensions are referred to as 0 or 1**
- 0 -> horizontal axis
- 1 -> vertical axis

### ndarray of single dimension: **numpy.arrange**

In [ ]:
n = np.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

This isn't exactly a multi-dimensional array as it only has a single dimension but it is a **numpy.ndarray** 

In [ ]:
type(n)

numpy.ndarray

### Creating a real multidimensional array by **reshape**ing existing $1$-dim array

In [ ]:
n.reshape(3, 9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [ ]:
n.reshape(3, 3, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

### Creating numpy arrays using existing python sequences: **numpy.asarray()**

In [ ]:
list = [[1, 2, 3, 4, 5], [11, 22, 33, 44, 55], [111, 222, 333, 444, 555]]
m = np.asarray(list)
m

array([[  1,   2,   3,   4,   5],
       [ 11,  22,  33,  44,  55],
       [111, 222, 333, 444, 555]])

## Converting images to Numpy Arrays
We'll use the **OpenCV** package, also referred to as **cv2**, for doing this.

In [ ]:
import cv2

the **cv2.imread** function expects two args for loading an image.
- The image itself(the path to the image to be precise)
- And *int* indicating whether it is to be loaded as a **grayscales** $(0)$ or as **BGR** $(1)$ (BGR in the exact same sequence, first layer has blue, 2nd green and 3rd red).

In [ ]:
img_grey = cv2.imread("Z:\Learning\Python_Projects\Web Mapping\Dataset\smallgray.png", 0)
img_grey

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

See the grayscale intensities in the 2-D array. The white (most intense) are 255 and 0 -> Black

In [ ]:
img_bgr = cv2.imread("Z:\Learning\Python_Projects\Web Mapping\Dataset\smallgray.png", 1)
img_bgr

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

This is the 3-D array of 
- Blue Layer
- Green Layer
- Red Layer

**!!!** One thing to remember is that the **layers are transposed**, ie, the rows are vertical and the columns are horizontal, and thats why each layer is $(5$ X $3)$ instead of $(3$ x $5)$ as it should've been.

### Conveting Numpy arrays to images: **cv2.imwrite**

In [ ]:
cv2.imwrite("new_smallgray.png", img_grey)

True

## Addressing elements in ndarray

### Indexing and slicing Numpy Arrays

Indexing and slicing are basically the same as we do with python lists

In [ ]:
n = img_grey
n

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [ ]:
n[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [ ]:
n[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [ ]:
n[2:, 2:4]

array([[255,  97]], dtype=uint8)

Lets check out the shape

In [ ]:
n.shape

(3, 5)

### Iteration 
There are two ways to iterate over a ndarray
- Row-wise or column-wise
- Element-wise

**Row-wise**

In [ ]:
for i in n:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


**Column-wise**

In [ ]:
for i in n.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


### **flat**tening a ndarray: n-D to 1-D
We can also convert a ndarray into a single dimensional array which can be used to iterate over the array **element-wise**

In [ ]:
for i in n.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


## Stacking and Splitting Numpy Arrays

### Stacking/Concatenating
There are (obviously) two ways of stacking ndarrays
- **hstack** will stack the 2 or more arrays horizontally
- **vstack** will stack them vertically

**!!!** Though we're concatenating multiple ndarrays these stack methods only take one argument. It takes a **tuple** of all the ndarrays to be concatenated.

Also, the ndarrays to be concatenated must have **same dimensions**.

In [ ]:
n_hcat = np.hstack((n, n))
n_hcat

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [ ]:
n_vcat = np.vstack((n, n, n))
n_vcat

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

### Splitting
This too can be done in two ways, horizontally (**hsplit**) and vertically (**vsplit**).

It takes a ndarray (the one to be split) and an integer $k$ and then divides the ndarray in $k$ equal ndarrays, horizontally or vertically (as per specified).

In [149]:
n_hsplit = np.hsplit(n, 5)
n_hsplit

[array([[187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182]], dtype=uint8)]

In [151]:
n_vsplit = np.vsplit(n_vcat, 3)
n_vsplit

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

Also, notice the type of data these split methods are returning

In [152]:
type(n_vsplit)

list

So **split** functions return a **python list of numpy arrays**, this implies that we can access each ndarray as we do with any python list

In [155]:
n_vsplit[2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)